# ── Prefix Key ──────────────────────────
unbind C-b
set -g prefix C-a
bind C-a send-prefix


# ── General Settings ─────────────────────
set -g mouse on
set-window-option -g mode-keys vi
set -g history-limit 10000
set -g base-index 0
setw -g pane-base-index 0
set -g set-clipboard on


# ── Keybinds ──────────────────────────────

bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection-no-clear

bind '\' split-window -h -c '#[pane_current_path}'
bind '-' split-window -v -c '#[pane_current_path}'

bind 'h' select-pane -L
bind 'l' select-pane -R
bind 'j' select-pane -D
bind 'k' select-pane -U

bind -r 'H' resize-pane -L 2
bind -r 'L' resize-pane -R 2
bind -r 'J' resize-pane -D 2
bind -r 'K' resize-pane -U 2

bind 'r' source-file ~/.config/tmux/tmux.conf

bind -T copy-mode-vi v send-keys -X begin-selection \; send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel \

# ── Status Bar ────────────────────────────
set -g status-position bottom
set -g status-interval 5
set -g status-left " #S "
set -g status-right " %H:%M %d-%b "


# ── Terminal Colors ──────────────────────
set -sa terminal-features ",xterm-256color:RGB"
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"


# ── Pane Borders ─────────────────────────
set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"


# ── Plugins ──────────────────────────────
set -g @plugin 'tmux-plugins/tpm'               # Plugin manager
set -g @plugin 'tmux-plugins/tmux-sensible'     # Default options

set -g @plugin 'tmux-plugins/tmux-resurrect'    # Sessions
set -g @plugin 'tmux-plugins/tmux-continuum'    # Auto save sessions

set -g @plugin 'sainnhe/tmux-fzf'               # Fuzzy finder

set -g @plugin 'catppuccin/tmux'                # Theme

set -g @plugin 'tmux-plugins/tmux-yank'         # Copy to clipboard

# ── Plugin config ───────────────────────

#Sessions
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

#Theme
set -g @catppuccin_flavor 'mocha'

#Utils











# ── Install plugins ───────────────────────
run '~/.tmux/plugins/tpm/tpm'
